config/routes.rb
RoSystems::Application.routes.draw do

  root :to => "users#login"
  match "sales/auto_complete_for_technician_delivery_person_name", :to => "sales#auto_complete_for_technician_delivery_person_name"
  match "sales/auto_complete_for_technician_installation_person_name", :to => "sales#auto_complete_for_technician_installation_person_name"
  match "sales/auto_complete_for_technician_enquiry_from", :to => "sales#auto_complete_for_technician_enquiry_from" 
  match "sales/auto_complete_for_sale_customer_name", :to => "sales#auto_complete_for_sale_customer_name" 
  match "customers/auto_complete_for_customer_name", :to => "customers#auto_complete_for_customer_name" 
  resources :assemblies

  match "user/new", :to => "users#new"
  match "home", :to => "users#home"
  match "user/create", :to => "users#create"
  match "user/check", :to => "users#check_login"
  match "logout", :to => "users#logout"
  match "user/change_password", :to => "users#change_password"
  match "user/set_password", :to => "users#set_password"
  match "user/show", :to => "users#show"
  match "user/delete/:id", :to => "users#destroy#:id", :as => "user/delete"
  match "user/citi_info", :to => "users#citi_info"
  match "sales/incentive", :to => "sales#incentive"
  match "sales/incentive_detail", :to => "sales#incentive_detail"
  match "user/insert_citi_info", :to => "users#insert_citi_info"

  match "product/new", :to => "products#new_product"
  match "product/create", :to => "products#create_product"
  match "product/edit/:id", :to => "products#edit_product#:id", :as => "product/edit" 
  match "product/delete/:id", :to => "products#destroy#:id", :as => "product/delete"
  match "product/update/:id", :to => "products#update_product#:id", :as => "product/update"
  match "product/stock", :to => "products#stock_detail"
  match "product/stock_transfer", :to => "products#stock_transfer"
  match "product/user_stock_transfer", :to => "products#user_stock_transfer"
  match "product/save_stock_transfer", :to => "products#save_stock_transfer",:via=>:post
  match "product/user_stock_transfer_from", :to => "products#user_stock_transfer_from"
  match "product/stock_transfer_details", :to => "products#stock_transfer_details"
  match "product/user_transfer", :to => "products#user_transfer"
  match "product/user_stock", :to => "products#user_stock"
  match "product/save_user_stock", :to => "products#save_user_stock",:via=>:post
  match "product/save_transfer_stock", :to => "products#save_transfer_stock",:via=>:post
  match "ordered_stock", :to => "products#ordered_stock_detail"
  match "ordered_stock_transfer", :to => "products#ordered_stock_transfer"
  match "print_stock", :to => "products#print_stock"
  match "product/test", :to => "products#test"

  match "technician/new", :to => "technicians#new_technician"
  match "technician/create", :to => "technicians#create_technician"
  match "technician/show", :to => "technicians#show"
  match "technician/edit/:id", :to => "technicians#edit_technician#:id", :as => "technician/edit"
  match "technician/delete/:id", :to => "technicians#destroy#:id", :as => "technician/delete"
  match "technician/update/:id", :to => "technicians#update_technician#:id", :as => "technician/update"

  match "order", :to => "orders#order"
  match "order/create", :to => "orders#create_order"
  match "order/edit/:id", :to => "orders#edit_order#:id", :as => "order/edit"
	match "order/show_order_status/:id", :to => "orders#show_order_status#:id", :as => "order/show_order_status"
  match "order/update/:id", :to => "orders#update_order#:id", :as => "order/update"
  match "print_order", :to => "orders#print_order"
  match "order_destroy/:id", :to => "orders#destroy_order#:id"
  match "product_row/:id" => "orders#product_row#:id"
  match "stock_row/:id" => "products#stock_row#:id"
  match "product_stock_row/:id" => "products#product_stock_row#:id"
  match "selected_company/:id" => "orders#selected_company#:id"
  match "selected_product/:id" => "orders#selected_product#:id"
  match "order/status", :to => "orders#order_status"
  match "ordered_status", :to => "orders#ordered_order_status"
  match "print_order_status", :to => "orders#print_order_status"
  match "order/status_details/:id", :to => "orders#order_status_details#:id"
  match "update_quantity/:id", :to => "orders#add_received_quantity#:id"
  match "update_same_quantity/:id", :to => "orders#update_same_received_quantity#:id"
  match "receive_quantity", :to => "orders#receive_quantity#:id"
  match "order/balance", :to => "orders#order_balance"
  match "ordered_order_balance", :to => "orders#ordered_order_balance"
  match "order/balance_detail/:id", :to => "orders#order_balance_details#:id"
  match "print_order_balance", :to => "orders#print_order_balance"
  match "print_company_pay", :to => "orders#print_company_pay"

  match "company/new", :to => "orders#new_company"
  match "company/show", :to => "orders#show_companies"
  match "company/create", :to => "orders#create_company"
  match "company/edit/:id", :to => "orders#edit_company#:id", :as => "company/edit"
  match "/company/delete/:id", :to => "orders#destroy_company#:id", :as => "company/delete"

  match "company/update/:id", :to => "orders#update_company#:id", :as => "company/update"
  match "ordered_show", :to => "orders#ordered_show_companies"
  match "print_company_list", :to => "orders#print_companies"

  match "customer/new", :to => "customers#new_customer"
  match "customer/create", :to=> "customers#create_customer"
  match "print_amc", :to=> "customers#print_amc"
  match "complaint", :to => "customers#complaint_form"
  match "customer/view/:id", :to => "customers#view_complaint#:id"
  match "customer/edit_complaint/:id", :to => "customers#edit_complaint#:id"
	match "customer/delete_complaint/:id", :to => "customers#delete_complaint#:id"
  match "add_complaint", :to => "customers#add_complaint"
  match "update_complaint", :to => "customers#update_complaint"
  match "customer/information/:id", :to => "customers#customer_information#:id"
  match "selected_customer/:id" => "customers#selected_customer#:id"
  match "customer/complaint_register", :to=> "customers#complaint_register"
  match "ordered_complaint_register", :to=> "customers#ordered_complaint_register"
  match "print_complaint_register", :to=> "customers#print_complaint_register"
  match "customer/service_form/:id", :to=> "customers#service_form#:id"
  match "customer/reprint_service_form/:id", :to=> "customers#reprint_service_form#:id"
  match "customer/product_row/:id" => "customers#product_row#:id"
  match "assemblies/parts_row/:id" => "assemblies#parts_row#:id"
  match "edit_product_row/:id/:product_id" => "customers#edit_product_row#:id#:product_id"
  match "selected_citi_info/:citi_name" => "customers#selected_citi_info#:citi_name"

  match "customer/process_complaint" => "customers#process_complaint"
  match "customer/balance_report" => "customers#balance_report"
  match "ordered_balance_report" => "customers#ordered_balance_report"
  match "print_customer_balance" => "customers#print_customer_balance_report"
  match "customer/balance_detail/:id", :to => "customers#customer_balance_details#:id"
  match "customer/pay_installment/:id", :to => "customers#pay_installment#:id"
  match "order/pay_installment/:id", :to => "customers#order_pay_installment#:id"
  match "customer/installment_pay", :to => "customers#installment_pay"
  match "customer/service_register", :to => "customers#service_register"
  match "ordered_service_register", :to => "customers#ordered_service_register"
  match "customer/service_detail/:id", :to => "customers#service_details#:id"
  match "customer/amc_expiry_report", :to => "customers#amc_expiry"
  match "ordered_amc_expiry", :to => "customers#ordered_amc_expiry"
  match "print_amc_expiry", :to => "customers#print_amc_expiry"
  match "customer/renew/:id", :to => "customers#renew_customer#:id"
  match "customer/update", :to=> "customers#update"
  match "customer/edit_amc/:id", :to => "customers#edit_amc#:id", :as => "customer/edit_amc"
  match "customer/view_amc/:id", :to => "customers#view_amc#:id", :as => "customer/view_amc"
  match "/update_amc/:id", :to => "customers#update_amc#:id", :as => "customer/update"
  
  match "customer/amc_not_serviced", :to => "customers#amc_not_serviced"
  match "ordered_amc_not_serviced", :to => "customers#ordered_amc_not_serviced"
  match "customer/show_amc", :to => "customers#show_amc",:as =>"customer/show_amc"
  match "customer/ordered_show_amc", :to => "customers#ordered_show_amc",:as =>"ordered_show_amc"
  match "amc_customer/delete/:id", :to => "customers#destroy#:id", :as => "amc_customer/delete"
  match "create_complaint/:id", :to => "customers#create_complaint#:id"
  match "print_customer_installment", :to => "customers#print_customer_installment"

  match"selected_bill_book_series/:id" => "Sales#selected_bill_book_series#:id"
  match "get_customer_details", :to => "sales#get_customer_details"
  match "get_amc_customer_details", :to => "customers#get_amc_customer_details"
  match "sales/sale", :to => "sales#sales"
  match "sales/create_bill", :to => "sales#create_bill"
  match "sales/edit/:id", :to => "sales#edit_sales_order#:id"
  match "sales/view/:id",:to => "sales#view_sales_order#:id"
  match "services/view/:id",:to => "sales#view_services_order#:id"
  match "sales/update/:id", :to => "sales#update_sales_order#:id", :as =>"sales/update"
  match "sales_destroy/:id", :to => "sales#sales_destroy#:id"
  match "customer_destroy/:id", :to => "customers#customer_destroy#:id"
  match "services_destroy/:id", :to => "sales#services_destroy#:id"
 
  match "sale_product_row/:id" => "sales#sale_product_row#:id"
  match "sale_add_payment_cheque/:id" => "sales#sale_add_payment_cheque#:id"
  match "selected_description/:id" => "sales#selected_description#:id"
  match "sales/sales_register", :to => "sales#sales_register"
  match "ordered_sales_register", :to => "sales#ordered_sales_register"

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :user_type
  validates :user_name, :presence => true
  validates :password, :presence => true,
                       :length => { :minimum => 4, :maximum => 10 },
                       :confirmation => true      
  validates :user_type_id, :presence => true
  
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
   has_one :user
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

### Check Authendication before calling any function except check_login and login
    before_filter :authenticate, :except => [ :check_login, :login ]
    before_filter :is_admin, :only => [ :show, :destroy, :new, :create ]
    ##before_filter :is_logged_in, :only => [ :login ]
    #     before_filter :service_access

### Generate New User form
  def new
    @user = User.new
  end

    def home
    end
### Insert Citi Info
  def insert_citi_info
     @city_info = CitiInfo.new(params[:citi_info])
     if @city_info.save
       redirect_to user_citi_info_path
     else
       flash[:notice] = "Please fill the all entries"
       redirect_to user_new_path
     end
   end
### Create User
  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to user_show_path
    else
      flash[:notice] = "Please fill the all entries"
      redirect_to user_new_path
    end
  end

  def login
  end

### Perform Login check
  def check_login
    @user = User.find(:first, :conditions => ["user_name = ? AND password = ?", params[:user_name], params[:password]])
    if !@user.nil?
      session[:user_id] = @user.id
          session[:user_type] = @user.is_admin
          redirect_to home_path
  else
      flash[:notice] = "Please enter correct username or password"
      redirect_to root_path
    end
  end

### logout user
  def logout
    reset_session
          session[:user_id] = nil
          session[:user_type] = nil
    redirect_to root_path
  end

### Generate Form for changing Password
  def change_password
    @user = User.new
  end

### Set New password to database
  def set_password
    @user = User.find(session[:user_id])
    if @user.password == params[:old_password]
      
      if @user.update_attribute(:password , params[:user][:password])
        redirect_to home_path
        flash[:notice] = "Password updated!"
      else
        flash[:notice] = "Please enter correct passwords"
        render user_change_password_path
      end
    else
      flash[:notice] = "Please enter your correct passwords"
      redirect_to user_change_password_path
    end
  end

### Show Users List
  def show
    @user = User.find(:all, :conditions => ["is_admin = 'FALSE'"])
  end


### Delete User
  def destroy
    begin
      user = User.find(params[:id])
      user.destroy
    rescue
    end
    redirect_to user_show_path
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/change_password.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="user-heading">Change Password</div>
    <% if flash[:notice] %>
      <div id="error">
        <%= flash[:notice] %>
      </div>
    <% else %>
      <div id="without-error">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="clear"></div>
    <%= form_for @user, :url => user_set_password_path do |f|%>

      <div class="user-fields">
        <div class="user-lables"><%= label_tag(:old_password) %></div>
        <div class="user-boxes"><%= password_field_tag('old_password',"" , :size => 30, :class => "selectboxLength") %></div>
      </div>
      <div class="clear"></div>
      <div class="user-fields">
          <div class="user-lables"><%= f.label :password %></div>
          <div class="user-boxes"><%= f.password_field :password, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="user-fields">
          <div class="user-lables">Confirm Password</div>
          <div class="user-boxes"><%= f.password_field :password_confirmation, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div id = "change-button">
        <%= f.submit "Change Password" %>
      </div>

    <% end %>
  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>

app/views/users/citi_info.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="user-heading">Create New User</div>
    <% if flash[:notice] %>
      <div id="error">
        <%= flash[:notice] %>
      </div>
    <% else %>
      <div id="without-error">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="clear"></div>
    <%= form_for :citi_info,:url => user_insert_citi_info_path  do |f|%>

      <div class="user-fields">
          <div class="user-lables"><%= f.label :city_name %></div>
          <div class="user-boxes"><%= f.text_field :city_name, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="user-fields">
          <div class="user-lables"><%= f.label :zip %></div>
          <div class="user-boxes"><%= f.text_field :zip, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="user-fields">
          <div class="user-lables"><%= f.label :std_code %></div>
          <div class="user-boxes"><%= f.text_field :std_code, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div id="submit-button">
        <%= f.submit %>
      </div>

    <% end %>
   </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>   

app/views/users/home.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
<%unless flash[:notice].blank? %> 
<div style="color:red;"><%=flash[:notice]%></div>
<%end%>
<div id="welcome", style="color:teal";>Welcome</div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>

app/views/users/login.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/login_header" %></div>
  <div class="clear"></div>
  <div id="login-wrapper">
    <div id="login-heading">Login</div>
    <% if flash[:notice] %>
      <div id="error">
        <%= flash[:notice] %>
      </div>
    <% else %>
      <div id="without-error">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="clear"></div>
    <form action="/user/check" method="post">
      <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      <div class="login-fields">
        <div class="login-lables">User Name</div>
        <div class="login-boxes">
          <%=  text_field_tag("user_name") %>
        </div>
      </div>
      <div class="clear"></div>
      <div class="login-fields">
        <div class="login-lables">Password</div>
        <div class="login-boxes">
          <%= password_field_tag("password") %>
        </div>
      </div>
      <div class="clear"></div>
      <div id="submit-button">
        <input type="submit" name="Submit" value="Login" >
      </div>
    </form>
  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>

app/views/users/new.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="user-heading">Create New User</div>
    <% if flash[:notice] %>
      <div id="error">
        <%= flash[:notice] %>
      </div>
    <% else %>
      <div id="without-error">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="clear"></div>
    <%= form_for @user, :url => user_create_path do |f|%>

      <div class="user-fields">
          <div class="user-lables"><%= f.label :user_name %></div>
          <div class="user-boxes"><%= f.text_field :user_name, :class => "selectboxLength" %></div>
      </div>
    
    <div class="user-fields">
          <div class="user-lables"><%= f.label :user_full_name %></div>
          <div class="user-boxes"><%= f.text_field :user_full_name, :class => "selectboxLength" %></div>
      </div>

    <div class="user-fields">
          <div class="user-lables"><%= f.label :user_type %></div>
          <div class="user-boxes"><%= collection_select(:user, :user_type_id, UserType.all, :id, :name, {:prompt => true}, :class => "selectboxLength" )%></div>
      </div>

              <%= check_box(:user, :is_admin)%>is_admin

      <div class="clear"></div>
      <div class="user-fields">
          <div class="user-lables"><%= f.label :password %></div>
          <div class="user-boxes"><%= f.password_field :password, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="user-fields">
          <div class="user-lables">Confirm Password</div>
          <div class="user-boxes"><%= f.password_field :password_confirmation, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div id="submit-button">
        <%= f.submit %>
      </div>

    <% end %>
    <div class="user-fields"><%= link_to 'Back', user_show_path %> </div>
  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>   

app/views/users/show.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="show-user-heading">Users List</div>
    <div class="clear"></div>
    <div id="show-user-first-row">
      <div class="serial-number-first">S. No.</div>
      <div class="show-user-name-first">User Name</div>
      <div class="show-user-full-first">User Full Name</div>
      <div class="show-user-password-first">Password</div>
      <div class="show-user-type-first">User Type</div>
      <div class="technicain-operation-first">Operations</div>
    </div>
    <div class="clear"></div>
    <% serial_number = 0 %>
    <% @user.each do |user| %>
        <%user_type = UserType.find(user[:user_type_id])%>
        <div class="show-user-rows">
        <div class="serial-numbers"><%= serial_number=(serial_number+1) %></div>
        <div class="show-user-names"><%= user.user_name %></div>
        <div class="show-user-full"><%= user.user_full_name %></div>
        <div class="show-user-password"><%= user.password %></div>
        <div class="show-user-type"><%= user_type.name %></div>
        <div class="show-user-operations"><%= link_to 'Destroy', user_delete_path(user), :confirm => 'Are you sure?', :method => :delete %></div>
      </div>
      <div class="clear"></div>
    <% end %>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
  <div class="clear"></div>
  <div id = "left-padding"><%= link_to "New User", user_new_path%></div>
  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>