config/routes.rb
RoSystems::Application.routes.draw do

  root :to => "users#login"
  match "sales/auto_complete_for_technician_delivery_person_name", :to => "sales#auto_complete_for_technician_delivery_person_name"
  match "sales/auto_complete_for_technician_installation_person_name", :to => "sales#auto_complete_for_technician_installation_person_name"
  match "sales/auto_complete_for_technician_enquiry_from", :to => "sales#auto_complete_for_technician_enquiry_from" 
  match "sales/auto_complete_for_sale_customer_name", :to => "sales#auto_complete_for_sale_customer_name" 
  match "customers/auto_complete_for_customer_name", :to => "customers#auto_complete_for_customer_name" 
  resources :assemblies

  match "user/new", :to => "users#new"
  match "home", :to => "users#home"
  match "user/create", :to => "users#create"
  match "user/check", :to => "users#check_login"
  match "logout", :to => "users#logout"
  match "user/change_password", :to => "users#change_password"
  match "user/set_password", :to => "users#set_password"
  match "user/show", :to => "users#show"
  match "user/delete/:id", :to => "users#destroy#:id", :as => "user/delete"
  match "user/citi_info", :to => "users#citi_info"
  match "sales/incentive", :to => "sales#incentive"
  match "sales/incentive_detail", :to => "sales#incentive_detail"
  match "user/insert_citi_info", :to => "users#insert_citi_info"

  match "product/new", :to => "products#new_product"
  match "product/create", :to => "products#create_product"
  match "product/edit/:id", :to => "products#edit_product#:id", :as => "product/edit" 
  match "product/delete/:id", :to => "products#destroy#:id", :as => "product/delete"
  match "product/update/:id", :to => "products#update_product#:id", :as => "product/update"
  match "product/stock", :to => "products#stock_detail"
  match "product/stock_transfer", :to => "products#stock_transfer"
  match "product/user_stock_transfer", :to => "products#user_stock_transfer"
  match "product/save_stock_transfer", :to => "products#save_stock_transfer",:via=>:post
  match "product/user_stock_transfer_from", :to => "products#user_stock_transfer_from"
  match "product/stock_transfer_details", :to => "products#stock_transfer_details"
  match "product/user_transfer", :to => "products#user_transfer"
  match "product/user_stock", :to => "products#user_stock"
  match "product/save_user_stock", :to => "products#save_user_stock",:via=>:post
  match "product/save_transfer_stock", :to => "products#save_transfer_stock",:via=>:post
  match "ordered_stock", :to => "products#ordered_stock_detail"
  match "ordered_stock_transfer", :to => "products#ordered_stock_transfer"
  match "print_stock", :to => "products#print_stock"
  match "product/test", :to => "products#test"

  match "technician/new", :to => "technicians#new_technician"
  match "technician/create", :to => "technicians#create_technician"
  match "technician/show", :to => "technicians#show"
  match "technician/edit/:id", :to => "technicians#edit_technician#:id", :as => "technician/edit"
  match "technician/delete/:id", :to => "technicians#destroy#:id", :as => "technician/delete"
  match "technician/update/:id", :to => "technicians#update_technician#:id", :as => "technician/update"

  match "order", :to => "orders#order"
  match "order/create", :to => "orders#create_order"
  match "order/edit/:id", :to => "orders#edit_order#:id", :as => "order/edit"
	match "order/show_order_status/:id", :to => "orders#show_order_status#:id", :as => "order/show_order_status"
  match "order/update/:id", :to => "orders#update_order#:id", :as => "order/update"
  match "print_order", :to => "orders#print_order"
  match "order_destroy/:id", :to => "orders#destroy_order#:id"
  match "product_row/:id" => "orders#product_row#:id"
  match "stock_row/:id" => "products#stock_row#:id"
  match "product_stock_row/:id" => "products#product_stock_row#:id"
  match "selected_company/:id" => "orders#selected_company#:id"
  match "selected_product/:id" => "orders#selected_product#:id"
  match "order/status", :to => "orders#order_status"
  match "ordered_status", :to => "orders#ordered_order_status"
  match "print_order_status", :to => "orders#print_order_status"
  match "order/status_details/:id", :to => "orders#order_status_details#:id"
  match "update_quantity/:id", :to => "orders#add_received_quantity#:id"
  match "update_same_quantity/:id", :to => "orders#update_same_received_quantity#:id"
  match "receive_quantity", :to => "orders#receive_quantity#:id"
  match "order/balance", :to => "orders#order_balance"
  match "ordered_order_balance", :to => "orders#ordered_order_balance"
  match "order/balance_detail/:id", :to => "orders#order_balance_details#:id"
  match "print_order_balance", :to => "orders#print_order_balance"
  match "print_company_pay", :to => "orders#print_company_pay"

  match "company/new", :to => "orders#new_company"
  match "company/show", :to => "orders#show_companies"
  match "company/create", :to => "orders#create_company"
  match "company/edit/:id", :to => "orders#edit_company#:id", :as => "company/edit"
  match "/company/delete/:id", :to => "orders#destroy_company#:id", :as => "company/delete"

  match "company/update/:id", :to => "orders#update_company#:id", :as => "company/update"
  match "ordered_show", :to => "orders#ordered_show_companies"
  match "print_company_list", :to => "orders#print_companies"

  match "customer/new", :to => "customers#new_customer"
  match "customer/create", :to=> "customers#create_customer"
  match "print_amc", :to=> "customers#print_amc"
  match "complaint", :to => "customers#complaint_form"
  match "customer/view/:id", :to => "customers#view_complaint#:id"
  match "customer/edit_complaint/:id", :to => "customers#edit_complaint#:id"
	match "customer/delete_complaint/:id", :to => "customers#delete_complaint#:id"
  match "add_complaint", :to => "customers#add_complaint"
  match "update_complaint", :to => "customers#update_complaint"
  match "customer/information/:id", :to => "customers#customer_information#:id"
  match "selected_customer/:id" => "customers#selected_customer#:id"
  match "customer/complaint_register", :to=> "customers#complaint_register"
  match "ordered_complaint_register", :to=> "customers#ordered_complaint_register"
  match "print_complaint_register", :to=> "customers#print_complaint_register"
  match "customer/service_form/:id", :to=> "customers#service_form#:id"
  match "customer/reprint_service_form/:id", :to=> "customers#reprint_service_form#:id"
  match "customer/product_row/:id" => "customers#product_row#:id"
  match "assemblies/parts_row/:id" => "assemblies#parts_row#:id"
  match "edit_product_row/:id/:product_id" => "customers#edit_product_row#:id#:product_id"
  match "selected_citi_info/:citi_name" => "customers#selected_citi_info#:citi_name"

  match "customer/process_complaint" => "customers#process_complaint"
  match "customer/balance_report" => "customers#balance_report"
  match "ordered_balance_report" => "customers#ordered_balance_report"
  match "print_customer_balance" => "customers#print_customer_balance_report"
  match "customer/balance_detail/:id", :to => "customers#customer_balance_details#:id"
  match "customer/pay_installment/:id", :to => "customers#pay_installment#:id"
  match "order/pay_installment/:id", :to => "customers#order_pay_installment#:id"
  match "customer/installment_pay", :to => "customers#installment_pay"
  match "customer/service_register", :to => "customers#service_register"
  match "ordered_service_register", :to => "customers#ordered_service_register"
  match "customer/service_detail/:id", :to => "customers#service_details#:id"
  match "customer/amc_expiry_report", :to => "customers#amc_expiry"
  match "ordered_amc_expiry", :to => "customers#ordered_amc_expiry"
  match "print_amc_expiry", :to => "customers#print_amc_expiry"
  match "customer/renew/:id", :to => "customers#renew_customer#:id"
  match "customer/update", :to=> "customers#update"
  match "customer/edit_amc/:id", :to => "customers#edit_amc#:id", :as => "customer/edit_amc"
  match "customer/view_amc/:id", :to => "customers#view_amc#:id", :as => "customer/view_amc"
  match "/update_amc/:id", :to => "customers#update_amc#:id", :as => "customer/update"
  
  match "customer/amc_not_serviced", :to => "customers#amc_not_serviced"
  match "ordered_amc_not_serviced", :to => "customers#ordered_amc_not_serviced"
  match "customer/show_amc", :to => "customers#show_amc",:as =>"customer/show_amc"
  match "customer/ordered_show_amc", :to => "customers#ordered_show_amc",:as =>"ordered_show_amc"
  match "amc_customer/delete/:id", :to => "customers#destroy#:id", :as => "amc_customer/delete"
  match "create_complaint/:id", :to => "customers#create_complaint#:id"
  match "print_customer_installment", :to => "customers#print_customer_installment"

  match"selected_bill_book_series/:id" => "Sales#selected_bill_book_series#:id"
  match "get_customer_details", :to => "sales#get_customer_details"
  match "get_amc_customer_details", :to => "customers#get_amc_customer_details"
  match "sales/sale", :to => "sales#sales"
  match "sales/create_bill", :to => "sales#create_bill"
  match "sales/edit/:id", :to => "sales#edit_sales_order#:id"
  match "sales/view/:id",:to => "sales#view_sales_order#:id"
  match "services/view/:id",:to => "sales#view_services_order#:id"
  match "sales/update/:id", :to => "sales#update_sales_order#:id", :as =>"sales/update"
  match "sales_destroy/:id", :to => "sales#sales_destroy#:id"
  match "customer_destroy/:id", :to => "customers#customer_destroy#:id"
  match "services_destroy/:id", :to => "sales#services_destroy#:id"
 
  match "sale_product_row/:id" => "sales#sale_product_row#:id"
  match "sale_add_payment_cheque/:id" => "sales#sale_add_payment_cheque#:id"
  match "selected_description/:id" => "sales#selected_description#:id"
  match "sales/sales_register", :to => "sales#sales_register"
  match "ordered_sales_register", :to => "sales#ordered_sales_register"

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_show_amc.html.erb
<% serial_number = 0 %>
<% if amc_customer.length>0 %>
  <% amc_customer.each do |customer| %>
    <!--<%if customer["amc_type"] != "others" %>-->
    <div class="show-user-row5">
      <div class="serial-numbers"> <%= serial_number = counter + 1 %> </div>
      <div class="show-amc-date"><%= (customer["contract_date"])%></div>
      <div class="show-amc-names"><%= customer["name"] %></div>
      <div class="show-amc-type"><%= customer["amc_type"] %></div>
      <div class="show-amc-address"><%= customer["address"]%></div>
      <div class="show-amc-model-name"><%= customer["model_name"] %></div>
      <div class="show-amc-amount"><%= customer["contract_amount"] %></div>
      <%if session[:user_type]%> 
        <div class="show-user-operation-amc1"><%= link_to 'View',customer_view_amc_path(customer) %>
        <%= link_to 'Edit', customer_edit_amc_path(customer) %>
        <%= link_to 'Delete', amc_customer_delete_path(customer), :confirm => 'Are   you sure?', :method => :delete %></div>
      <%else%>
        <div class="show-user-operation-amc1" align="center" ><%= link_to 'View',customer_view_amc_path(customer) %>
        <%# link_to 'Edit',"/edit_amc/#{customer.id}" %><%# link_to 'Delete', amc_customer_delete_path(customer), :confirm => 'Are   you sure?', :method => :delete %></div>
     
      <%end%>
      <% unless customer["created_by"].blank? %>
        <% user = User.find(customer["created_by"]).user_name%>
        <div class="show-created-by"><%= user %></div>
      <% end %>
      
    <% counter = counter + 1 %>
    </div> 
    <div class="clear"></div>
    <!--<% end %>-->
    <% end %>
<% else %>
  <div id = "rows-not-found">"No AMC found"</div>
  <div class="clear">
	
</div>
<% end %>
<% current_page = (Float(counter) / 25).ceil %>
<div class="clear"></div>
<%= render :partial => "layouts/get_paginated", :locals => { :current_page => current_page, :total_pages => total_pages, :function_name => "ordered_show_amc" }%>

app/views/customers/edit_complaint.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
 <!-- <%unless flash[:notice].blank? %> 
       <div style="color:red;"><%=flash[:notice]%></div>
  <%end%>-->
    <div id="complaint-heading">Edit Complaint</div>
    <div id="without-error"></div>
    <div class="clear"></div>
    <%=form_for :complaint, :url => update_complaint_path  do |f| %>


      <div class="complaint-fields">
<!--           <div class="complaint-lables"><%= f.label :id %></div> -->
          <div class="complaint-boxes"><%= f.hidden_field :id, :class => "selectboxLength", :name => "complaint[id]",:readonly => :true %></div>
      </div>
 <%if @complaint.customer.amc_type != "others"%>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Name</div>
          <div class="complaint-boxes"><%= text_field :customer, :name, :class => "selectboxLength",:value =>@complaint.customer.name,:readonly => true %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Customer Type </div>
          <div class="complaint-boxes"><%= text_field :customer,:amc_type, :class => "selectboxLength",:value =>@complaint.customer.amc_type ,:readonly => true %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">House No </div>
          <div class="complaint-boxes"><%= text_field :customer,:house_number, :class => "selectboxLength",:value =>@complaint.customer.house_number ,:readonly => true %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Street</div>
          <div class="complaint-boxes"><%= text_field :customer,:street, :class => "selectboxLength",:value =>@complaint.customer.street ,:readonly => true %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Colony</div>
          <div class="complaint-boxes"><%= text_field :customer,:colony, :class => "selectboxLength",:value =>@complaint.customer.colony ,:readonly => true %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Land Mark</div>
          <div class="complaint-boxes"><%= text_field :customer,:landmark, :class => "selectboxLength",:value =>@complaint.customer.landmark ,:readonly => true %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">City</div>
          <div class="complaint-boxes"><%= text_field :customer,:city, :class => "selectboxLength",:value =>@complaint.customer.city ,:readonly => true %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Zip Code</div>
          <div class="complaint-boxes"><%= text_field :customer,:zipcode , :class => "selectboxLength",:value =>@complaint.customer.zipcode  ,:readonly => true %></div>
      </div>
    <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">State</div>
          <div class="complaint-boxes"><%= text_field :customer,:state, :class => "selectboxLength",:value =>@complaint.customer.state ,:readonly => true %></div>
      </div><div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Mobile No</div>
          <div class="complaint-boxes"><%= text_field :customer,:mobile_number , :class => "selectboxLength",:value =>@complaint.customer.mobile_number  ,:readonly => true %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Phone No</div>
          <div class="complaint-boxes"><%= text_field :customer,:phone_number, :class => "selectboxLength",:value =>@complaint.customer.phone_number ,:readonly => true %></div>
      </div><div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Model Name</div>
          <div class="complaint-boxes"><%= text_field :customer,:model_name , :class => "selectboxLength",:value =>@complaint.customer.model_name  ,:readonly => true %></div>
      </div>
<%else%>
      <div class="complaint-fields">
<!--         <div class="complaint-lables">Name</div> -->
          <div class="complaint-boxes"><%= hidden_field :customer, :id, :class => "selectboxLength",:value =>@complaint.customer.id ,:readonly => true%></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Name<span class="necessary">*</span></div>
          <div class="complaint-boxes"><%= text_field :customer, :name, :class => "selectboxLength",:value =>@complaint.customer.name %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Customer Type </div>
          <div class="complaint-boxes"><%= text_field :customer,:amc_type, :class => "selectboxLength",:value =>@complaint.customer.amc_type ,:readonly => true %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">House No </div>
          <div class="complaint-boxes"><%= text_field :customer,:house_number, :class => "selectboxLength",:value =>@complaint.customer.house_number  %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Street</div>
          <div class="complaint-boxes"><%= text_field :customer,:street, :class => "selectboxLength",:value =>@complaint.customer.street  %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Colony</div>
          <div class="complaint-boxes"><%= text_field :customer,:colony, :class => "selectboxLength",:value =>@complaint.customer.colony  %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Land Mark</div>
          <div class="complaint-boxes"><%= text_field :customer,:landmark, :class => "selectboxLength",:value =>@complaint.customer.landmark  %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">City<span class="necessary">*</span></div>
          <div class="complaint-boxes"><%= text_field :customer,:city, :class => "selectboxLength",:value =>@complaint.customer.city  %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Zip Code</div>
          <div class="complaint-boxes"><%= text_field :customer,:zipcode , :class => "selectboxLength",:value =>@complaint.customer.zipcode   %></div>
      </div>
    <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">State<span class="necessary">*</span></div>
          <div class="complaint-boxes"><%= text_field :customer,:state, :class => "selectboxLength",:value =>@complaint.customer.state  %></div>
      </div><div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Mobile No</div>
          <div class="complaint-boxes"><%= text_field :customer,:mobile_number , :class => "selectboxLength",:value =>@complaint.customer.mobile_number   %></div>
      </div>
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Phone No</div>
          <div class="complaint-boxes"><%= text_field :customer,:phone_number, :class => "selectboxLength",:value =>@complaint.customer.phone_number  %></div>
      </div><div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Model Name<span class="necessary">*</span></div>
          <div class="complaint-boxes"><%= text_field :customer,:model_name , :class => "selectboxLength",:value =>@complaint.customer.model_name   %></div>
      </div>
<%end%>      
      <div class="clear"></div>
      <div class="complaint-fields">
        <div class="complaint-lables">Complaint No</div>
          <div class="complaint-boxes"><%= f.text_field :complaint_no, :class => "selectboxLength",:readonly => true %></div>
      </div>
      <div class="clear"></div>
         <div class="complaint-fields">
          <div class="complaint-lables"><%= f.label :date %></div>
          <div class="complaint-boxes"><%=text_field_tag "complaints[date]",@complaint.date, :class => "selectboxLength", :name => "complaint[date]",:id => 'complaint_date_field'%>
            <span class="date_button"><%= submit_tag("...", { :name => 'button', :id => 'complaint_date', :type => "button" }) %></span></div>
        </div>
       
        <div class="clear"></div>
        <div class="clear"></div>
        <div class="complaint-fields">
          <div class="complaint-lables"><%= f.label :description %></div>
          <div class="complaint-boxes"><%= f.text_area :description, :rows => 2, :cols => 34, :class => "selectboxLength", :name => "complaint[description]" %></div>
        </div>
      

      <div class="clear"></div>
      <div id = "complaint-button">
        <%= submit_tag "Edit Complaint" %>
      </div>

    <% end %>
  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>
<script type="text/javascript">
  Zapatec.Calendar.setup({
            inputField     :    "complaint_date_field",     // id of the input field
            ifFormat       :    "%m/%d/%Y",     // format of the input field
            button         :    "complaint_date",  // What will trigger the popup of the calendar
            showsTime      :     false      //don't show time, only date
    });
</script>

app/views/customers/order_pay_installment.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
<% param = params[:id].split('&')%>
    <div id="installment-pay-heading">Installment</div>
    <div id="without-error"></div>
    <div class="clear"></div>
    <%= form_for :payments, :url => customer_installment_pay_path, :html => { :onsubmit => "return check_installment()" } do |f| %>
      <%= f.hidden_field :id, :value => "#{param[0]}" %>
      <%= hidden_field :act, :actions, :value => "#{param[1]}" %>
      <div class="installment-pay-fields">
        <div class="installment-pay-lables">Payment Date<span class='necessary'>*</span></div>
        <div class="installment-pay-boxes">
          <%= f.text_field :pay_date , :value => Date.today.strftime('%m/%d/%Y'), :class => "selectboxLength" %>
          <span class="date_button"><%= submit_tag("...", { :name => 'button', :id => 'pay_date', :type => "button" }) %></span>
        </div>
      </div>
      <!--<div class="clear"></div>
      <div class="installment-pay-fields">
        <div class="installment-pay-lables">Remaining Amount  </div>
        <div class="installment-pay-boxes"><%="#{@balance}"%></div>
      </div>-->
      <div class="installment-pay-fields">
        <div class="installment-pay-lables">Select Amount </div>
          <span><%= radio_button "payments", "select_amount", "recd_amount", :onclick=>"Enable()" %>Received Amount</span>
        <span><%= radio_button "payments", "select_amount", "paid_amount",:onclick=>"Disable();" %>Paid Amount</span>
      </div>
      <div class="clear"></div>
      
        <div class="installment-pay-fields", id="paid_amount_div", style=display:none>
        <div class="installment-pay-lables">Paid Amount<span class='necessary'>*</span></div>
        <div class="installment-pay-boxes"><%= f.text_field :paid_amount, :value => 0, :class => "selectboxLength" %></div>
        </div>
      
      <div class="clear"></div>
      <div class="clear"></div>
      
      
        <div class="installment-pay-fields", id="recd_amount_div", style=display:none>
        <div class="installment-pay-lables">Received Amount<span class='necessary'>*</span></div>
        <div class="installment-pay-boxes"><%= f.text_field :recd_amount, :value => 0, :class => "selectboxLength" %></div>
        </div>
      
<div class="clear"></div>


      <div class="clear"></div>
      

    <div class="installment-pay-fields">
          <%= check_box(:payments, :is_cash, :onclick =>'javascript:installment_cash_payment();')%>By Cash
          <%= check_box(:payments, :is_cheque, :onclick =>'javascript:installment_cheque_payment();')%>By Cheque
          <%= check_box(:payments, :is_by_transfer, :onclick =>'javascript:installment_transfer_payment();')%>By Transfer
          <%= check_box(:payments, :is_by_card, :onclick =>'javascript:installment_card_payment();')%>By Card
    </div>

        <div class="installment-pay-fields", id="cash_div", style=display:none>
        <div class="installment-pay-lables">Cash Amount <span class='necessary'>*</span></div>
        <div class="installment-pay-boxes"><%= text_field :payments, :cash_amount, :class => "selectboxLength" %></div>
        </div>
        <div class="clear"></div> 

    <div id="c1" ></div>
        <div class="clear"></div>
        <div class="installment-pay-fields" id="cheque_div", style=display:none><%= link_to "Add Cheque Details", 'javascript:void(0);', :onclick => "sales_add_payment_cheque()" %></div>

        <div class="installment-pay-fields", id="transfer_div1", style=display:none>
        <div class="installment-pay-lables">Transfer Amount <span class='necessary'>*</span></div>
        <div class="installment-pay-boxes"><%= text_field :payments, :transfer_amount, :class => "selectboxLength" %></div>
        </div>
        <div class="clear"></div>

        <div class="installment-pay-fields", id="transfer_div2", style=display:none>
        <div class="installment-pay-lables">To Account No <span class='necessary'>*</span></div>
        <div class="installment-pay-boxes"> <%= text_field :payments, :transfer_to_account_no,  :class => "selectboxLength" %></div>
        </div>
        <div class="clear"></div>

        <div class="installment-pay-fields", id="card_div", style=display:none>
        <div class="installment-pay-lables">Card Paid Amount <span class='necessary'>*</span></div>
        <div class="installment-pay-boxes"><%= text_field :payments, :card_paid_amount, :class => "selectboxLength" %></div>
        </div>
        <div class="clear"></div>


        <div class="installment-pay-fields">
          <div class="installment-pay-lables">Next Payment Date </div>
            <div class="installment-pay-boxes">
               <%= f.text_field :next_pay_date, :class => "selectboxLength" %>
              <span class="date_button"><%= submit_tag("...", { :name => 'button', :id => 'next_pay_date', :type => "button" }) %></span>
            </div>
         </div>
      <div class="clear"></div>

      <div id="installment-pay-button">
        <%= submit_tag "Paid" %>
      </div>
    <% end %>
    <div class="installment-pay-fields">
      <%= param[1] == "order_balance_details" ? link_to('Back', order_balance_path) : link_to('Back',  customer_balance_report_path) %>
    </div>

  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>
<script type="text/javascript">
  Zapatec.Calendar.setup({
            inputField     :    "payments_pay_date",     // id of the input field
            ifFormat       :    "%m/%d/%Y",     // format of the input field
            button         :    "pay_date",  // What will trigger the popup of the calendar
            showsTime      :     false      //don't show time, only date
    });

  Zapatec.Calendar.setup({
            inputField     :    "payments_next_pay_date",     // id of the input field
            ifFormat       :    "%m/%d/%Y",     // format of the input field
            button         :    "next_pay_date",  // What will trigger the popup of the calendar
            showsTime      :     false      //don't show time, only date
    });
</script>
<script type="text/javascript">


function Enable(){
    var y=document.getElementById("payments_recd_amount")
    var x=document.getElementById("payments_paid_amount")
    y.show();  $("recd_amount_div").show();
    x.hide();  $("paid_amount_div").hide();

}
function Disable(){
    var y=document.getElementById("payments_recd_amount")
    var x=document.getElementById("payments_paid_amount")
    y.hide(); $("recd_amount_div").hide();
    x.show(); $("paid_amount_div").show();

}
</script>