config/routes.rb
RoSystems::Application.routes.draw do

  root :to => "users#login"
  match "sales/auto_complete_for_technician_delivery_person_name", :to => "sales#auto_complete_for_technician_delivery_person_name"
  match "sales/auto_complete_for_technician_installation_person_name", :to => "sales#auto_complete_for_technician_installation_person_name"
  match "sales/auto_complete_for_technician_enquiry_from", :to => "sales#auto_complete_for_technician_enquiry_from" 
  match "sales/auto_complete_for_sale_customer_name", :to => "sales#auto_complete_for_sale_customer_name" 
  match "customers/auto_complete_for_customer_name", :to => "customers#auto_complete_for_customer_name" 
  resources :assemblies

  match "user/new", :to => "users#new"
  match "home", :to => "users#home"
  match "user/create", :to => "users#create"
  match "user/check", :to => "users#check_login"
  match "logout", :to => "users#logout"
  match "user/change_password", :to => "users#change_password"
  match "user/set_password", :to => "users#set_password"
  match "user/show", :to => "users#show"
  match "user/delete/:id", :to => "users#destroy#:id", :as => "user/delete"
  match "user/citi_info", :to => "users#citi_info"
  match "sales/incentive", :to => "sales#incentive"
  match "sales/incentive_detail", :to => "sales#incentive_detail"
  match "user/insert_citi_info", :to => "users#insert_citi_info"

  match "product/new", :to => "products#new_product"
  match "product/create", :to => "products#create_product"
  match "product/edit/:id", :to => "products#edit_product#:id", :as => "product/edit" 
  match "product/delete/:id", :to => "products#destroy#:id", :as => "product/delete"
  match "product/update/:id", :to => "products#update_product#:id", :as => "product/update"
  match "product/stock", :to => "products#stock_detail"
  match "product/stock_transfer", :to => "products#stock_transfer"
  match "product/user_stock_transfer", :to => "products#user_stock_transfer"
  match "product/save_stock_transfer", :to => "products#save_stock_transfer",:via=>:post
  match "product/user_stock_transfer_from", :to => "products#user_stock_transfer_from"
  match "product/stock_transfer_details", :to => "products#stock_transfer_details"
  match "product/user_transfer", :to => "products#user_transfer"
  match "product/user_stock", :to => "products#user_stock"
  match "product/save_user_stock", :to => "products#save_user_stock",:via=>:post
  match "product/save_transfer_stock", :to => "products#save_transfer_stock",:via=>:post
  match "ordered_stock", :to => "products#ordered_stock_detail"
  match "ordered_stock_transfer", :to => "products#ordered_stock_transfer"
  match "print_stock", :to => "products#print_stock"
  match "product/test", :to => "products#test"

  match "technician/new", :to => "technicians#new_technician"
  match "technician/create", :to => "technicians#create_technician"
  match "technician/show", :to => "technicians#show"
  match "technician/edit/:id", :to => "technicians#edit_technician#:id", :as => "technician/edit"
  match "technician/delete/:id", :to => "technicians#destroy#:id", :as => "technician/delete"
  match "technician/update/:id", :to => "technicians#update_technician#:id", :as => "technician/update"

  match "order", :to => "orders#order"
  match "order/create", :to => "orders#create_order"
  match "order/edit/:id", :to => "orders#edit_order#:id", :as => "order/edit"
	match "order/show_order_status/:id", :to => "orders#show_order_status#:id", :as => "order/show_order_status"
  match "order/update/:id", :to => "orders#update_order#:id", :as => "order/update"
  match "print_order", :to => "orders#print_order"
  match "order_destroy/:id", :to => "orders#destroy_order#:id"
  match "product_row/:id" => "orders#product_row#:id"
  match "stock_row/:id" => "products#stock_row#:id"
  match "product_stock_row/:id" => "products#product_stock_row#:id"
  match "selected_company/:id" => "orders#selected_company#:id"
  match "selected_product/:id" => "orders#selected_product#:id"
  match "order/status", :to => "orders#order_status"
  match "ordered_status", :to => "orders#ordered_order_status"
  match "print_order_status", :to => "orders#print_order_status"
  match "order/status_details/:id", :to => "orders#order_status_details#:id"
  match "update_quantity/:id", :to => "orders#add_received_quantity#:id"
  match "update_same_quantity/:id", :to => "orders#update_same_received_quantity#:id"
  match "receive_quantity", :to => "orders#receive_quantity#:id"
  match "order/balance", :to => "orders#order_balance"
  match "ordered_order_balance", :to => "orders#ordered_order_balance"
  match "order/balance_detail/:id", :to => "orders#order_balance_details#:id"
  match "print_order_balance", :to => "orders#print_order_balance"
  match "print_company_pay", :to => "orders#print_company_pay"

  match "company/new", :to => "orders#new_company"
  match "company/show", :to => "orders#show_companies"
  match "company/create", :to => "orders#create_company"
  match "company/edit/:id", :to => "orders#edit_company#:id", :as => "company/edit"
  match "/company/delete/:id", :to => "orders#destroy_company#:id", :as => "company/delete"

  match "company/update/:id", :to => "orders#update_company#:id", :as => "company/update"
  match "ordered_show", :to => "orders#ordered_show_companies"
  match "print_company_list", :to => "orders#print_companies"

  match "customer/new", :to => "customers#new_customer"
  match "customer/create", :to=> "customers#create_customer"
  match "print_amc", :to=> "customers#print_amc"
  match "complaint", :to => "customers#complaint_form"
  match "customer/view/:id", :to => "customers#view_complaint#:id"
  match "customer/edit_complaint/:id", :to => "customers#edit_complaint#:id"
	match "customer/delete_complaint/:id", :to => "customers#delete_complaint#:id"
  match "add_complaint", :to => "customers#add_complaint"
  match "update_complaint", :to => "customers#update_complaint"
  match "customer/information/:id", :to => "customers#customer_information#:id"
  match "selected_customer/:id" => "customers#selected_customer#:id"
  match "customer/complaint_register", :to=> "customers#complaint_register"
  match "ordered_complaint_register", :to=> "customers#ordered_complaint_register"
  match "print_complaint_register", :to=> "customers#print_complaint_register"
  match "customer/service_form/:id", :to=> "customers#service_form#:id"
  match "customer/reprint_service_form/:id", :to=> "customers#reprint_service_form#:id"
  match "customer/product_row/:id" => "customers#product_row#:id"
  match "assemblies/parts_row/:id" => "assemblies#parts_row#:id"
  match "edit_product_row/:id/:product_id" => "customers#edit_product_row#:id#:product_id"
  match "selected_citi_info/:citi_name" => "customers#selected_citi_info#:citi_name"

  match "customer/process_complaint" => "customers#process_complaint"
  match "customer/balance_report" => "customers#balance_report"
  match "ordered_balance_report" => "customers#ordered_balance_report"
  match "print_customer_balance" => "customers#print_customer_balance_report"
  match "customer/balance_detail/:id", :to => "customers#customer_balance_details#:id"
  match "customer/pay_installment/:id", :to => "customers#pay_installment#:id"
  match "order/pay_installment/:id", :to => "customers#order_pay_installment#:id"
  match "customer/installment_pay", :to => "customers#installment_pay"
  match "customer/service_register", :to => "customers#service_register"
  match "ordered_service_register", :to => "customers#ordered_service_register"
  match "customer/service_detail/:id", :to => "customers#service_details#:id"
  match "customer/amc_expiry_report", :to => "customers#amc_expiry"
  match "ordered_amc_expiry", :to => "customers#ordered_amc_expiry"
  match "print_amc_expiry", :to => "customers#print_amc_expiry"
  match "customer/renew/:id", :to => "customers#renew_customer#:id"
  match "customer/update", :to=> "customers#update"
  match "customer/edit_amc/:id", :to => "customers#edit_amc#:id", :as => "customer/edit_amc"
  match "customer/view_amc/:id", :to => "customers#view_amc#:id", :as => "customer/view_amc"
  match "/update_amc/:id", :to => "customers#update_amc#:id", :as => "customer/update"
  
  match "customer/amc_not_serviced", :to => "customers#amc_not_serviced"
  match "ordered_amc_not_serviced", :to => "customers#ordered_amc_not_serviced"
  match "customer/show_amc", :to => "customers#show_amc",:as =>"customer/show_amc"
  match "customer/ordered_show_amc", :to => "customers#ordered_show_amc",:as =>"ordered_show_amc"
  match "amc_customer/delete/:id", :to => "customers#destroy#:id", :as => "amc_customer/delete"
  match "create_complaint/:id", :to => "customers#create_complaint#:id"
  match "print_customer_installment", :to => "customers#print_customer_installment"

  match"selected_bill_book_series/:id" => "Sales#selected_bill_book_series#:id"
  match "get_customer_details", :to => "sales#get_customer_details"
  match "get_amc_customer_details", :to => "customers#get_amc_customer_details"
  match "sales/sale", :to => "sales#sales"
  match "sales/create_bill", :to => "sales#create_bill"
  match "sales/edit/:id", :to => "sales#edit_sales_order#:id"
  match "sales/view/:id",:to => "sales#view_sales_order#:id"
  match "services/view/:id",:to => "sales#view_services_order#:id"
  match "sales/update/:id", :to => "sales#update_sales_order#:id", :as =>"sales/update"
  match "sales_destroy/:id", :to => "sales#sales_destroy#:id"
  match "customer_destroy/:id", :to => "customers#customer_destroy#:id"
  match "services_destroy/:id", :to => "sales#services_destroy#:id"
 
  match "sale_product_row/:id" => "sales#sale_product_row#:id"
  match "sale_add_payment_cheque/:id" => "sales#sale_add_payment_cheque#:id"
  match "selected_description/:id" => "sales#selected_description#:id"
  match "sales/sales_register", :to => "sales#sales_register"
  match "ordered_sales_register", :to => "sales#ordered_sales_register"

app/helpers/orders_helper.rb
module OrdersHelper
def get_total_paidamount(order_obj)
order_obj.order_payments.sum('paid_amount')
end

end

app/views/orders/_edit_product_row.html.erb
<div class="dynamic-product-names"><%= collection_select(:product_name, count, Product.find(:all, :select => ["DISTINCT(name)"], :conditions => "is_enable = TRUE"), :name, :name, {:prompt => true}, {:onchange=> "var e=$('product_name_count'); product_select(e.options[e.selectedIndex].value,'count')", :name => "product[name][]", :class => "dynamic-name-box-length"})%></div>
<div class="dynamic-product-description"><%= collection_select(:description, count, Product.find(:all, :conditions => "is_enable = TRUE"), :id, :description, {:prompt => true}, {:name => "product[description][]", :class => "dynamic-description-box-length", :disabled => true} ) %></div>
<div class="dynamic-product-quantity"><%= text_field :product,:quantity, :onblur => "service_get_total(count)", :id => "product_quantity_count",:name => "product[quantity][]",:class => "dynamic-box-length" %></div>
<div class="dynamic-product-rate"><%= text_field :product,:rate, :onblur => "service_get_total(count)", :id => "product_rate_count", :name => "product[rate][]", :class => "dynamic-box-length" %></div>
<div class="dynamic-product-total"><%= text_field :product,:total, :disabled => true, :id => "product_total_count", :value => 0, :class => "dynamic-box-length" %></div>

app/views/orders/_order_balance.html.erb
<% if orders.length > 0 %>
  <% orders.each do |status| %>
    <div class = "order-balance-rows">
      <div class = "serial-numbers"><%= serial_number=(counter+1) %></div>
      <div class = "order-balance-company-names"><%= link_to "#{status["company_name"]}",'javascript:void(0);', :onclick => "get_balance_detail(#{status["company_id"]},0)" %></div>
      <div class = "order-balance-company-address"><%= status["address"] %></div>
      <div class="order-balance-balances">
        <%
          balance = status["balance"]
          if(balance < 0.0)
        %>
            <div id = "remaning">
        <% else %>
            <div id = "exceed">
        <% end %>
              <%= balance %></div>
      </div>
      <div id="<%= status["company_id"] %>"></div>
      <% counter = counter + 1 %>
    </div>
    <div class="clear"></div>
  <% end %>
<% else %>
  <div id = "rows-not-found">"No Record found"</div>
  <div class="clear"></div>
<% end %>
<% current_page = (Float(counter) / 25).ceil %>
<div class="clear"></div>
<%= render :partial => "layouts/get_paginated", :locals => { :current_page => current_page, :total_pages => total_pages, :function_name => "ordered_order_balance_report" }%>

app/views/orders/_show_companies.html.erb
<%serial_number = 0%>
<% if companies.length > 0 %>
  <% companies.each do |company| %>
      <div class="show-company-rows">
      <div class="serial-numbers1"><%= serial_number=(serial_number+1) %></div>
      <div class="show-company-names"><%= company["name"] %></div>
      <div class="show-company-addresses"><%= company["address"] %></div>
      <div class="show-user-operations1"><%= link_to 'Edit', company_edit_path(company["id"]) %></div><div class="show-user-operations2"><%= link_to 'Delete', company_delete_path(company), :confirm => 'Are you sure?', :method => :delete %></div>
    </div>
    <% counter = counter + 1 %>
    <div class="clear"></div>
  <% end %>
<% else %>
  <div id = "rows-not-found">"No Company found"</div>
  <div class="clear"></div>
<% end %>
<% current_page = (Float(counter) / 25).ceil %>
<div class="clear"></div>
<%= render :partial => "layouts/get_paginated", :locals => { :current_page => current_page, :total_pages => total_pages, :function_name => "ordered_show_company" }%>

app/views/orders/add_received_quantity.html.erb
<%= form_for :order_product, :url => receive_quantity_path, :html => { :onsubmit => "return check_quantity();" } do |f| %>
  <%= hidden_field :order_product, :id, :value => "#{@orders["order_product_id"]}" %>
  <div class="serial-fields">
    <div class="serial-lables">Ordered Quantity </div>
    <div class="serial-boxes"><%= text_field :order_product, :ordered_quantity, :value => "#{@orders["ordered_quantity"]}", :onkeyup => "check_quantity_serial()", :class => "selectboxLength" %></div>
  </div>
  <div class="clear"></div>
  <div class="serial-fields">
    <div class="serial-lables">Received Quantity </div>
    <div class="serial-boxes"><%= text_field :order_product, :received_quantity, :value => 0, :onkeyup => "check_quantity_serial()",:class => "selectboxLength" %></div>
  </div>
  <div class="clear"></div>
  <div class="serial-fields">
    <div class="serial-lables">Previously Received Quantity </div>
    <div class="serial-boxes">
      <%= hidden_field :order_product, :previous_quantity, :value => "#{@orders["received_quantity"]}", :disabled => true %>
      <%= @orders["received_quantity"] %>
    </div>
  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
  <div id="add_serial"></div>
  <div class="clear"></div>
  <div id="serial-button">
    <%= submit_tag "Add" %>
  </div>
  <div class="clear"></div>
<% end %>

app/views/orders/edit_company.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="technician-heading">Edit Company</div>
    <% if flash[:notice] %>
      <div id="error">
        <%= flash[:notice] %>
      </div>
    <% else %>
      <div id="without-error">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="clear"></div>
    <%= form_for @company, :url => company_update_path, :html => { :onsubmit => "return check_company_fields()" } do |f|%>

      <div class="technician-fields">
        <div class="technician-lables"><%= f.label :name %><span class="necessary">*</span></div>
        <div class="technician-boxes"><%= f.text_field :name, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="technician-fields">
        <div class="technician-lables"><%= f.label :house_number %></div>
        <div class="technician-boxes"><%= f.text_field :house_number, :class => "selectboxLength" %></div>
      </div>
      <div class="technician-fields">
        <div class="technician-lables"><%= f.label :street %></div>
        <div class="technician-boxes"><%= f.text_field :street, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="technician-fields">
        <div class="technician-lables"><%= f.label :colony %></div>
        <div class="technician-boxes"><%= f.text_field :colony, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="technician-fields">
        <div class="technician-lables"><%= f.label :landmark %></div>
        <div class="technician-boxes"><%= f.text_field :landmark, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="technician-fields">
        <div class="technician-lables"><%= f.label :city %><span class="necessary">*</span></div>
        <div class="technician-boxes"><%= f.text_field :city, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="technician-fields">
        <div class="technician-lables"><%= f.label :zipcode %></div>
        <div class="technician-boxes"><%= f.text_field :zipcode, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="technician-fields">
        <div class="technician-lables"><%= f.label :state %><span class="necessary">*</span></div>
        <div class="technician-boxes"><%= f.text_field :state, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div id="technician-button">
        <%= f.submit %>
      </div>

    <% end %>
    <div class="technician-fields"><%= link_to 'Back', company_show_path %> </div>
  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>

app/views/orders/order.html.erb
<% if session[:order_id].present? %>
  <% order_id = session[:order_id] %>
  <% session[:order_id] = nil %>
  <script type="text/javascript">
    window.onload = print_order(<%= order_id %>);
  </script>
<% end %>
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="order-heading">Purchase Order</div>
    <div id="without-error"></div>
    <div class="clear"></div>
    <%=form_for :order, :url => order_create_path, :html => { :onsubmit => "return check_fields()" } do |f| %>
      <div class="order-fields">
        <div class="order-lables">Company Name<span class="necessary">*</span></div>
        <div class="order-boxes"><%= collection_select(:company, :id, Company.all(:order => ["name ASC"]), :id, :name, {:prompt => true}, { :onchange=> "var e=$('company_id'); company_select(e.options[e.selectedIndex].value)", :name => "order[company_id]", :class => "selectboxLength" } )%></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">House Number </div>
        <div class="order-boxes"><%= text_field :company, :house_number, :disabled => true, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">Street </div>
        <div class="order-boxes"><%= text_field :company, :street, :disabled => true, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">Colony </div>
        <div class="order-boxes"><%= text_field :company, :colony, :disabled => true, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">Landmark </div>
        <div class="order-boxes"><%= text_field :company, :landmark, :disabled => true, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">City </div>
        <div class="order-boxes"><%= text_field :company, :city, :disabled => true, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">Zipcode </div>
        <div class="order-boxes"><%= text_field :company, :zipcode, :disabled => true, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">State </div>
        <div class="order-boxes"><%= text_field :company, :state, :disabled => true, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">Date(mm/dd/yyyy)<span class="necessary">*</span></div>
        <div class="order-boxes"><%= f.text_field :order_date, :value => Date.today.strftime('%m/%d/%Y'), :class => "selectboxLength"%>
        <span class="date_button"><%= submit_tag("...", { :name => 'button', :id => 'order_date', :type => "button" }) %></span></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">Contact Person </div>
        <div class="order-boxes"><%= text_field :order, :contact_person, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">Mobile Number </div>
        <div class="order-boxes"><%= text_field :order, :mobile_number, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">Phone Number</div>
        <div class="order-boxes"><%= text_field :order, :phone_number, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div id="dynamic-product-first-row">
        <div class="serial-number-first">S. No.</div>
        <div class="dynamic-name-first">Products/Parts</div>
        <div class="dynamic-description-first">Desciption</div>
        <div class="dynamic-quantity-first">Quantity</div>
        <div class="dynamic-rate-first">Rate</div>
        <div class="dynamic-total-first">Total</div>
      </div>
      <div class="clear"></div>
      <div id="1"></div>
      <div class="clear"></div>
      <div class="dynamic_rows"><%= link_to "Add", 'javascript:void(0);', :onclick => "add_row()" %></div>
      <div class="clear"></div>
      <div class="order-fields">
        <div class="order-lables">Total </div>
        <div class="order-boxes"><%= text_field :order, :total_amount, :value=> 0, :disabled => true, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
          <div class="order-lables">Payment Date(mm/dd/yyyy)</div>
          <div class="order-boxes"><%= text_field :order_payments, :date, :value => Date.today.strftime('%m/%d/%Y'), :class => "selectboxLength" %>
          <span class="date_button"><%= submit_tag("...", { :name => 'button', :id => 'payment_date', :type => "button" }) %></span></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
          <div class="order-lables">Amount Paid<span class='necessary'>*</span></div>
          <div class="order-boxes"><%= text_field :order_payments, :paid_amount,:value => 0, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div class="order-fields">
          <div class="order-lables">Remarks </div>
          <div class="order-boxes"><%= text_area :order_payments, :remarks, :rows => 2, :cols => 34, :class => "selectboxLength" %></div>
      </div>
      <div class="clear"></div>
      <div id="order-button">
          <%= submit_tag "Create Order" %>
      </div>
    <% end %>
  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>
<script type="text/javascript">
  Zapatec.Calendar.setup({
            inputField     :    "order_order_date",     // id of the input field
            ifFormat       :    "%m/%d/%Y",     // format of the input field
            button         :    "order_date",  // What will trigger the popup of the calendar
            showsTime      :     false      //don't show time, only date
    });

  Zapatec.Calendar.setup({
            inputField     :    "order_payments_date",     // id of the input field
            ifFormat       :    "%m/%d/%Y",     // format of the input field
            button         :    "payment_date",  // What will trigger the popup of the calendar
            showsTime      :     false      //don't show time, only date
    });

  window.onload = add_row();
</script>

app/views/orders/order_status_details.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="amc-expiry-heading">Order Status Detail</div>
    <div id="order-status-detail-first-row">
      <div class="serial-number-first">S. No.</div>
      <div class="order-status-detail-name-first">Products/Parts</div>
      <div class="order-status-detail-description-first">Description</div>
      <div class="order-status-detail-qunatity-first">Ordered Quantity</div>
      <div class="order-status-detail-qunatity-first">Received Quantity</div>
      <div class="order-status-detail-qunatity-first">Remaining Quantity</div>
      <div class="order-status-detail-update-first">Update Quantity</div>
    </div>
    <div class="clear"></div>
    <% counter = 0 %>
    <% if @orders.length > 0 %>
      <% @orders.each do |status| %>
        <div class= "order-status-detail-rows" >
          <div class="serial-numbers"><%= serial_number=(counter+1) %></div>
          <div class="order-status-detail-names"><%= status["product_name"] %></div>
          <div class="order-status-detail-descriptions"><%= status["product_description"] %></div>
          <div class="order-status-detail-qunatities"><%= status["ordered_quantity"] %></div>
          <div class="order-status-detail-qunatities"><%= status["received_quantity"] %></div>
          <div class="order-status-detail-qunatities"><%= status["remain_quantity"] %></div>
          <div class="order-status-detail-updates">
                <%= link_to image_tag("plus.jpeg", :width => 20, :height => 20),'javascript:void(0);', :onclick => "add_remaining_quantity(#{status["order_product_id"]},#{status["product_with_serial"]})" %>
              <% if !status["product_with_serial"] %>
                <%= link_to "same",'javascript:void(0);', :onclick => "add_same_remaining_quantity(#{status["order_product_id"]})" %>
              <% end %>
          </div>
          <div id = "<%= status["order_product_id"] %>"></div>
          <% counter = counter + 1 %>
        </div>
        <div class="clear"></div>
      <% end %>
    <% else %>
      <div id = "rows-not-found">" No Details Found "</div>
      <div class="clear"></div>
    <% end %>
     <div class="order-status-detail-rows"><%= link_to 'Back', order_status_path %> </div>
  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>

app/views/orders/print_company_pay.html.erb
<html style="background :white;">
<body style="background :white">
<div id = "print-wrapper">
  <div style="font-size :18px; text-align :center; font-weight :bold;">H<sub>2</sub>O Solutions</div>
  <div style="padding-bottom :10px;"></div>
  <div class="clear"></div>
  <div style="text-align :center; font-size :16px; font-weight :bold;">Order Payment</div>
  <div style="padding-bottom :10px;"></div>
  <div class="clear"></div>

  <div id="print-table-wrapper">
    <table style="text-align :left;" width="495px" cellspacing="5px">
      <tr>
        <th width="200px" style="padding-left :100px;">Company Name</th>
        <td><%= @company_name %></td>
      </tr>
      <tr>
        <th width="200px" style="padding-left :100px;">Address</th>
        <td><%= @address %></td>
      </tr>
      <tr>
        <th width="200px" style="padding-left :100px;">Payment Date(mm/dd/yyyy)</th>
        <td><%= @pay_date %></td>
      </tr>
      <tr>
          <th width="200px" style="padding-left :100px;">Paid Amount</th>
          <td><%= @paid_amount %></td>
      </tr>
      <tr>
          <th width="200px" style="padding-left :100px;">Received Amount</th>
          <td><%= @recd_amount %></td>
      </tr>

    </table>
  </div>
  <div class="clear"></div>
</div>
<script type="text/javascript">
  window.onload = window.print();
</script>