config/routes.rb
RoSystems::Application.routes.draw do

  root :to => "users#login"
  match "sales/auto_complete_for_technician_delivery_person_name", :to => "sales#auto_complete_for_technician_delivery_person_name"
  match "sales/auto_complete_for_technician_installation_person_name", :to => "sales#auto_complete_for_technician_installation_person_name"
  match "sales/auto_complete_for_technician_enquiry_from", :to => "sales#auto_complete_for_technician_enquiry_from" 
  match "sales/auto_complete_for_sale_customer_name", :to => "sales#auto_complete_for_sale_customer_name" 
  match "customers/auto_complete_for_customer_name", :to => "customers#auto_complete_for_customer_name" 
  resources :assemblies

  match "user/new", :to => "users#new"
  match "home", :to => "users#home"
  match "user/create", :to => "users#create"
  match "user/check", :to => "users#check_login"
  match "logout", :to => "users#logout"
  match "user/change_password", :to => "users#change_password"
  match "user/set_password", :to => "users#set_password"
  match "user/show", :to => "users#show"
  match "user/delete/:id", :to => "users#destroy#:id", :as => "user/delete"
  match "user/citi_info", :to => "users#citi_info"
  match "sales/incentive", :to => "sales#incentive"
  match "sales/incentive_detail", :to => "sales#incentive_detail"
  match "user/insert_citi_info", :to => "users#insert_citi_info"

  match "product/new", :to => "products#new_product"
  match "product/create", :to => "products#create_product"
  match "product/edit/:id", :to => "products#edit_product#:id", :as => "product/edit" 
  match "product/delete/:id", :to => "products#destroy#:id", :as => "product/delete"
  match "product/update/:id", :to => "products#update_product#:id", :as => "product/update"
  match "product/stock", :to => "products#stock_detail"
  match "product/stock_transfer", :to => "products#stock_transfer"
  match "product/user_stock_transfer", :to => "products#user_stock_transfer"
  match "product/save_stock_transfer", :to => "products#save_stock_transfer",:via=>:post
  match "product/user_stock_transfer_from", :to => "products#user_stock_transfer_from"
  match "product/stock_transfer_details", :to => "products#stock_transfer_details"
  match "product/user_transfer", :to => "products#user_transfer"
  match "product/user_stock", :to => "products#user_stock"
  match "product/save_user_stock", :to => "products#save_user_stock",:via=>:post
  match "product/save_transfer_stock", :to => "products#save_transfer_stock",:via=>:post
  match "ordered_stock", :to => "products#ordered_stock_detail"
  match "ordered_stock_transfer", :to => "products#ordered_stock_transfer"
  match "print_stock", :to => "products#print_stock"
  match "product/test", :to => "products#test"

  match "technician/new", :to => "technicians#new_technician"
  match "technician/create", :to => "technicians#create_technician"
  match "technician/show", :to => "technicians#show"
  match "technician/edit/:id", :to => "technicians#edit_technician#:id", :as => "technician/edit"
  match "technician/delete/:id", :to => "technicians#destroy#:id", :as => "technician/delete"
  match "technician/update/:id", :to => "technicians#update_technician#:id", :as => "technician/update"

  match "order", :to => "orders#order"
  match "order/create", :to => "orders#create_order"
  match "order/edit/:id", :to => "orders#edit_order#:id", :as => "order/edit"
	match "order/show_order_status/:id", :to => "orders#show_order_status#:id", :as => "order/show_order_status"
  match "order/update/:id", :to => "orders#update_order#:id", :as => "order/update"
  match "print_order", :to => "orders#print_order"
  match "order_destroy/:id", :to => "orders#destroy_order#:id"
  match "product_row/:id" => "orders#product_row#:id"
  match "stock_row/:id" => "products#stock_row#:id"
  match "product_stock_row/:id" => "products#product_stock_row#:id"
  match "selected_company/:id" => "orders#selected_company#:id"
  match "selected_product/:id" => "orders#selected_product#:id"
  match "order/status", :to => "orders#order_status"
  match "ordered_status", :to => "orders#ordered_order_status"
  match "print_order_status", :to => "orders#print_order_status"
  match "order/status_details/:id", :to => "orders#order_status_details#:id"
  match "update_quantity/:id", :to => "orders#add_received_quantity#:id"
  match "update_same_quantity/:id", :to => "orders#update_same_received_quantity#:id"
  match "receive_quantity", :to => "orders#receive_quantity#:id"
  match "order/balance", :to => "orders#order_balance"
  match "ordered_order_balance", :to => "orders#ordered_order_balance"
  match "order/balance_detail/:id", :to => "orders#order_balance_details#:id"
  match "print_order_balance", :to => "orders#print_order_balance"
  match "print_company_pay", :to => "orders#print_company_pay"

  match "company/new", :to => "orders#new_company"
  match "company/show", :to => "orders#show_companies"
  match "company/create", :to => "orders#create_company"
  match "company/edit/:id", :to => "orders#edit_company#:id", :as => "company/edit"
  match "/company/delete/:id", :to => "orders#destroy_company#:id", :as => "company/delete"

  match "company/update/:id", :to => "orders#update_company#:id", :as => "company/update"
  match "ordered_show", :to => "orders#ordered_show_companies"
  match "print_company_list", :to => "orders#print_companies"

  match "customer/new", :to => "customers#new_customer"
  match "customer/create", :to=> "customers#create_customer"
  match "print_amc", :to=> "customers#print_amc"
  match "complaint", :to => "customers#complaint_form"
  match "customer/view/:id", :to => "customers#view_complaint#:id"
  match "customer/edit_complaint/:id", :to => "customers#edit_complaint#:id"
	match "customer/delete_complaint/:id", :to => "customers#delete_complaint#:id"
  match "add_complaint", :to => "customers#add_complaint"
  match "update_complaint", :to => "customers#update_complaint"
  match "customer/information/:id", :to => "customers#customer_information#:id"
  match "selected_customer/:id" => "customers#selected_customer#:id"
  match "customer/complaint_register", :to=> "customers#complaint_register"
  match "ordered_complaint_register", :to=> "customers#ordered_complaint_register"
  match "print_complaint_register", :to=> "customers#print_complaint_register"
  match "customer/service_form/:id", :to=> "customers#service_form#:id"
  match "customer/reprint_service_form/:id", :to=> "customers#reprint_service_form#:id"
  match "customer/product_row/:id" => "customers#product_row#:id"
  match "assemblies/parts_row/:id" => "assemblies#parts_row#:id"
  match "edit_product_row/:id/:product_id" => "customers#edit_product_row#:id#:product_id"
  match "selected_citi_info/:citi_name" => "customers#selected_citi_info#:citi_name"

  match "customer/process_complaint" => "customers#process_complaint"
  match "customer/balance_report" => "customers#balance_report"
  match "ordered_balance_report" => "customers#ordered_balance_report"
  match "print_customer_balance" => "customers#print_customer_balance_report"
  match "customer/balance_detail/:id", :to => "customers#customer_balance_details#:id"
  match "customer/pay_installment/:id", :to => "customers#pay_installment#:id"
  match "order/pay_installment/:id", :to => "customers#order_pay_installment#:id"
  match "customer/installment_pay", :to => "customers#installment_pay"
  match "customer/service_register", :to => "customers#service_register"
  match "ordered_service_register", :to => "customers#ordered_service_register"
  match "customer/service_detail/:id", :to => "customers#service_details#:id"
  match "customer/amc_expiry_report", :to => "customers#amc_expiry"
  match "ordered_amc_expiry", :to => "customers#ordered_amc_expiry"
  match "print_amc_expiry", :to => "customers#print_amc_expiry"
  match "customer/renew/:id", :to => "customers#renew_customer#:id"
  match "customer/update", :to=> "customers#update"
  match "customer/edit_amc/:id", :to => "customers#edit_amc#:id", :as => "customer/edit_amc"
  match "customer/view_amc/:id", :to => "customers#view_amc#:id", :as => "customer/view_amc"
  match "/update_amc/:id", :to => "customers#update_amc#:id", :as => "customer/update"
  
  match "customer/amc_not_serviced", :to => "customers#amc_not_serviced"
  match "ordered_amc_not_serviced", :to => "customers#ordered_amc_not_serviced"
  match "customer/show_amc", :to => "customers#show_amc",:as =>"customer/show_amc"
  match "customer/ordered_show_amc", :to => "customers#ordered_show_amc",:as =>"ordered_show_amc"
  match "amc_customer/delete/:id", :to => "customers#destroy#:id", :as => "amc_customer/delete"
  match "create_complaint/:id", :to => "customers#create_complaint#:id"
  match "print_customer_installment", :to => "customers#print_customer_installment"

  match"selected_bill_book_series/:id" => "Sales#selected_bill_book_series#:id"
  match "get_customer_details", :to => "sales#get_customer_details"
  match "get_amc_customer_details", :to => "customers#get_amc_customer_details"
  match "sales/sale", :to => "sales#sales"
  match "sales/create_bill", :to => "sales#create_bill"
  match "sales/edit/:id", :to => "sales#edit_sales_order#:id"
  match "sales/view/:id",:to => "sales#view_sales_order#:id"
  match "services/view/:id",:to => "sales#view_services_order#:id"
  match "sales/update/:id", :to => "sales#update_sales_order#:id", :as =>"sales/update"
  match "sales_destroy/:id", :to => "sales#sales_destroy#:id"
  match "customer_destroy/:id", :to => "customers#customer_destroy#:id"
  match "services_destroy/:id", :to => "sales#services_destroy#:id"
 
  match "sale_product_row/:id" => "sales#sale_product_row#:id"
  match "sale_add_payment_cheque/:id" => "sales#sale_add_payment_cheque#:id"
  match "selected_description/:id" => "sales#selected_description#:id"
  match "sales/sales_register", :to => "sales#sales_register"
  match "ordered_sales_register", :to => "sales#ordered_sales_register"

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :order_products
  has_many :product_serial_numbers
  has_many :service_products
  has_many :sale_products, :as => :product_reference
  has_many :product_stocks
  has_many :sales

  validates :name, :presence => true
  validates :description, :presence => true
  validates :current_stock, :presence => true, :numericality => true

### Get Stock Details in a particular order
  def self.get_stock_detail( params )
    stock_detail = []
    begin
      products = ""
      unless params[:order_by] == "quantity desc" || params[:order_by] == "quantity asc"
        products = Product.all(:conditions => ["name ilike ? AND description ilike ? AND is_enable = TRUE", "#{params[:name]}%", "#{params[:description]}%"], :order => "#{params[:order_by]}")
      else
        products = Product.all(:conditions => ["name ilike ? AND description ilike ? AND is_enable = TRUE", "%#{params[:name]}%", "%#{params[:description]}%"])
      end
      unless products.blank?
        products.each do |product|
          detail = {}
          detail["product_name"] = product.name
          detail["description"] = product.description
          detail["product_id"] = product.id
          ordered_products = product.order_products
          total_quantity = 0
          total_amount = 0.0
          ordered_products.each do |p| 
             if p.received_quantity != nil
              total_quantity = (total_quantity + p.received_quantity) 
              total_amount = total_amount + p.rate * p.received_quantity
             end
          end
          detail["average_rate"] = total_quantity == 0 ? 0.0 : (total_amount / total_quantity).round(2) 
          with_serial = product.is_serial_number
          if with_serial
            received_quantity = product.product_serial_numbers.count("product_id", :conditions => ["is_sold = FALSE"])
            #detail["quantity"] = received_quantity
            detail["quantity"] = (product.current_stock)
          else
            #received_quantity = product.order_products.sum("received_quantity")
            #sold_quantity = product.sale_products.sum("quantity")
            #detail["quantity"] = received_quantity - sold_quantity + Integer(product.current_stock)
            detail["quantity"] = (product.current_stock)
          end
          stock_detail << detail
        end
      end
    rescue
        return 0
    end
    if params[:order_by] == "quantity desc"
      stock_detail.sort_by{ |quantity| quantity["quantity"] }.reverse!
    elsif params[:order_by] == "quantity asc"
      stock_detail.sort_by{ |quantity| quantity["quantity"] }
    else
      stock_detail.sort_by{ |product_name| product_name["product_name"] }
      #stock_detail.sort_by{ |quantity| quantity["quantity"] }.reverse!
      #stock_detail
    end
  end
  

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_stock_detail.html.erb
<% if stocks.length > 0 %>
  <% stocks.each do |stock| %>
    <div class="stock-detail-rows">
      <div class="serial-numbers"><%= serial_number=(counter+1) %></div>
      <div class="stock-detail-names"><%= stock["product_name"] %></div>
      <div class="stock-detail-description"><%= stock["description"] %></div>
      <div class="stock-detail-quantity"><%= stock["quantity"] %></div>
      <div class="stock-detail-quantity"><%= stock["average_rate"] %></div>
      <div class="stock-detail-operations-first"><%= link_to "Edit", product_edit_path(stock["product_id"]) %></div>
      <div class="stock-detail-operations-second"><%= link_to 'Destroy', product_delete_path(stock["product_id"]), :confirm => 'Are you sure?', :method => :delete %></div>
      <% counter = counter + 1 %>
    </div>
    <div class="clear"></div>
  <% end %>
<% else %>
  <div id = "rows-not-found">" No Details Found "</div>
  <div class="clear"></div>
<% end %>
  <div class="bottom_padding"></div>  <div class="bottom_padding"></div>
  <div class="clear"></div>
<div id = "left-padding"><%= link_to "New Product/Part", product_new_path%></div>
<% current_page = (Float(counter) / 25).ceil %>
<div class="clear"></div>
<%= render :partial => "layouts/get_paginated", :locals => { :current_page => current_page, :total_pages => total_pages, :function_name => "ordered_stock" }%>

app/views/products/_user_stock.html.erb
 <% if @product_stock != nil %>
  <%  stock = @product_stock %>
    <div class="stock-detail-rows">
      <div class="serial-numbers"><%= serial_number=(counter+1) %></div>
      <div class="stock-detail-names"><%= stock.product.name unless stock.product.nil? %></div>
      <div class="stock-detail-description"><%= stock.product.description unless stock.product.nil? %></div>
      <div class="stock-detail-quantity"><%= stock.stock_quantity %></div>
      <div class="stock-detail-names"><%= stock.product_serial_number.serial_number %></div>
      
     
      <% counter = counter + 1 %>
    </div>
    <div class="clear"></div>

<% else %>
  <div id = "rows-not-found">" No Details Found "</div>
  <div class="clear"></div>
<% end %>
  <div class="bottom_padding"></div>  <div class="bottom_padding"></div>
  <div class="clear"></div>


<div class="pagination">
      <%= will_paginate(@product_stock) %>
    </div>

app/views/products/ordered_stock_transfer.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="stock-transfer-datails-heading">User Stock</div>
     <div class="bottom_padding"></div>
     <div class="bottom_padding"></div>
     <% if flash[:notice] %>
      <div id="error">
        <%= flash[:notice] %>
      </div>
    <% else %>
      <div id="without-error">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="clear"></div>
    <fieldset>
      <legend>Serach By:</legend>
      <div class="stock-lables">Products/Parts </div>
      <div class="stock-boxes"><input type="text" id="name" class="search-length" onkeyup="ordered_stock_transfer(this);"></div>
      <div class="stock-lables">Description </div>
      <div class="stock-boxes"><input type="text" id="description" class="search-length" onkeyup="ordered_stock_transfer(this);"></div>
    </fieldset>
    <div class="clear"></div><br/>
     <div class="order-fields">
        <div class="order-lables">Technician<span class="necessary">*</span></div>
        <div class="order-boxes"><%= collection_select(:stock, :technician_id, Technician.all, :id, :name, {:prompt => true}, { :onchange=> "common_ajax_call('#{product_user_transfer_path}','stock-content',{'technician_id':this.value}); ", :class => "selectboxLength" } )%></div>
     </div>
    <div class="clear"></div>
    <div id="stock-detail-first-row">
      <div class="serial-numbers">S. No.</div>
      <div class="stock-detail-names" d="name desc" onclick="ordered_stock_transfer(this);">Products/Parts</div>
      <div class="stock-detail-description">Description</div>
      <div class="stock-detail-quantity">Quantity</div>
      <div class="stock-detail-quantity-first">Serial Number</div>
      <!--<div class="stock-detail-operation-first">Challen No.</div>-->
    </div>
    
    <div id="stock-content">
       <%= render :partial => "products/user_stock_detail", :locals => { :stocks => @product_stock, :counter => 0, :total_pages => 0}%>
    </div>
    <div class="clear"></div>
    
    <div class="bottom_padding"></div>
    <div class="clear"></div>
    
  </div>
  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>
<script type="text/javascript">
  //$("name").value = "";
 // $("description").value = "";
//window.onload = ordered_stock_transfer($);
</script>

app/views/products/stock_transfer_details.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="stock-transfer-datails-heading">Stock Transfer Details</div>
     <div class="bottom_padding"></div>
     <div class="bottom_padding"></div>
     <fieldset>
      <legend>Serach By:</legend>
      <div class="stock-lables">Products/Parts </div>
      <div class="stock-boxes"><input type="text" id="name" class="search-length" onkeyup="ordered_stock_transfer(this);"></div>
      <div class="stock-lables">Description </div>
      <div class="stock-boxes"><input type="text" id="description" class="search-length" onkeyup="ordered_stock_transfer(this);"></div>
    </fieldset>
    <div class="clear"></div><br/>
     <div class="order-fields">
        <div class="order-lables">Technician<span class="necessary">*</span></div>
        <div class="order-boxes"><%= collection_select(:stock, :technician_id, Technician.all, :id, :name, {:prompt => true}, { :onchange=> "common_ajax_call('#{product_user_transfer_path}','stock-content',{'technician_id':this.value}); ", :class => "selectboxLength" } )%></div>
      </div>
    <div class="clear"></div>
    <div id="stock-detail-first-row">
      <div class="serial-number-first">S. No.</div>
      <div class="stock-detail-name-first" id="name desc">Products/Parts</div>
      <div class="stock-detail-description-first">Description</div>
      <div class="stock-detail-quantity-first">Quantity</div>
      <div class="stock-detail-quantity-first" id="average rate">Serial Number</div>
      <!--<div class="stock-detail-operation-first">Challen No.</div>-->
    </div>
    <div id="stock-content">
    <%= render :partial => "products/user_stock_detail", :locals => { :stocks => @product_stock, :counter => 0, :total_pages => 0}%>
    </div>
    
    <div class="bottom_padding"></div>
    <div class="clear"></div>
    <div class="bottom_padding"></div>
    </div>
    <div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>

app/views/products/user_stock_transfer.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="stock-heading">User Stock Transfer</div>
    <div class="bottom_padding"></div>
    <div class="bottom_padding"></div>
    <div class="clear"></div>
    <% if flash[:notice] %>
      <div id="error">
        <%= flash[:notice] %>
      </div>
    <% else %>
      <div id="without-error">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <div class="clear"></div>
    <%=form_for :stock, :url => product_save_stock_transfer_path,:html => { :onsubmit => "return valDrop()"}  do |f| %>
    <div class="clear"></div>
    <div class="order-fields">
       <div class="order-boxes"><%= collection_select(:stock, :technician_id, Technician.all(:order => ["name ASC"]), :id, :name, {:prompt => true}, { :onchange=> "common_ajax_call('#{product_user_stock_transfer_from_path}','stock-content',{'technician_id':this.value}); ", :class => "selectboxLength" } )%>	To	<%= collection_select(:stock1, :technician_id, Technician.all(:order => ["name ASC"]), :id, :name, {:prompt => true}, { :onchange=> "common_ajax_call('#{product_user_stock_transfer_path}','stock-content',{'technician_id':this.value}); ", :class => "selectboxLength" } )%>
      </div>
    </div>
      <div class="clear"></div>
      <div id="dynamic-product-first-row">
        <div class="serial-number-first">S. No.</div>
        <div class="dynamic-name-first">Products/Parts</div>
        <div class="dynamic-description-first">Desciption</div>
        <div class="dynamic-rate-first">Serial Number</div>
        <div class="dynamic-quantity-first">Quantity</div>
        
        
      </div>
      <div class="clear">
      </div>
      <div class="clear"></div>
      <div id="1"></div>
      <div class="clear"></div>
      <div class="dynamic_rows"><%= link_to "Add", 'javascript:void(0);', :onclick => "add_product_stock_row()" %></div>
      <div class="clear"></div>
      
      <div class="clear"></div>
      <div id="order-button">
          <%= submit_tag "Stock transfer" %>
      </div>
    <% end %>
<div id = "left-padding"><%= link_to "Stock Transfer List", product_stock_transfer_details_path%></div>
  </div>

  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>


<script type="text/javascript">
function valDrop() {
 var checking_status = true;
 
 select_person("stock_technician_id") ? "" : checking_status = false;
 select_person("stock1_technician_id") ? "" : checking_status = false;

 if(!checking_status)
  {
   alert("Please select Technician from the drop-down list.");
   
  }
else{}
  return checking_status;
} 
</script>

app/views/products/user_stock_transfer_from.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="stock-heading">User Stock Transfer</div>
    <div class="bottom_padding"></div>
    <div class="bottom_padding"></div>
    <div class="clear"></div>
    <%=form_for :stock, :url => user_stock_transfer_path,:html => { :onsubmit => "return valDrop()"}  do |f| %>
    <!-- <div class="sales-fields">
        <div class="sales-lables">Stock Transfer<span class="necessary">*</span></div>
        <div class="sales-boxes">
        <span><%= radio_button "stock", "user_type", "1" %>To</span>
        <span><%= radio_button "stock", "user_type", "2" %>From</span></div>
      </div>
     <div class="order-fields">
        <div class="order-lables">Technician<span class="necessary">*</span></div>
        <div class="order-boxes"><%= collection_select(:stock, :technician_id, Technician.all, :id, :name, {:prompt => true}, { :onchange=> "common_ajax_call('#{}','dynamic-product-first-row',{'technician_id':'technician_id'}); ", :class => "selectboxLength" } )%></div>
      </div>-->
      <div class="clear"></div>
     <div class="order-fields">
       <div class="order-boxes"><%= collection_select(:stock, :technician_id, Technician.all, :id, :name, {:prompt => true}, { :onchange=> "common_ajax_call('#{}','stock-content',{'technician_id':this.value}); ", :class => "selectboxLength" } )%>	To	<%= collection_select(:stock1, :technician_id, Technician.all, :id, :name, {:prompt => true}, { :onchange=> "common_ajax_call('#{}','stock-content',{'technician_id':this.value}); ", :class => "selectboxLength" } )%>
      </div>
    </div>
      <div class="clear"></div>
      <div id="dynamic-product-first-row">
        <div class="serial-number-first">S. No.</div>
        <div class="dynamic-name-first">Products/Parts</div>
        <div class="dynamic-description-first">Desciption</div>
        <div class="dynamic-rate-first">Serial Number</div>
        <div class="dynamic-quantity-first">Quantity</div>
        
        
      </div>
      <div class="clear">
      </div>
      <div class="clear"></div>
      <div id="1"></div>
      <div class="clear"></div>
      <div class="dynamic_rows"><%= link_to "Add", 'javascript:void(0);', :onclick => "add_product_stock_row()" %></div>
      <div class="clear"></div>
      
      <div class="clear"></div>
      <div id="order-button">
          <%= submit_tag "Stock transfer" %>
      </div>
    <% end %>
<div id = "left-padding"><%= link_to "Stock Transfer List", product_stock_transfer_details_path%></div>
  </div>

  <div class="clear"></div>
  <div class="bottom_padding"></div>
</div>
<div class="clear"></div>
<div id = "header" align="center"><%= render "layouts/footer" %></div>


<script type="text/javascript">
function valDrop() {
 var checking_status = true;
 
 select_person("stock_technician_id") ? "" : checking_status = false;
 select_person("stock1_technician_id") ? "" : checking_status = false;

 if(!checking_status)
  {
   alert("Please select Technician from the drop-down list.");
   
  }
else{}
  return checking_status;
} 
</script>

app/views/products/user_transfer.html.erb
<div id = "wrapper">
  <div id = "header"><%= render "layouts/common_header" %></div>
  <div class="clear"></div>
  <div id="inner-wrapper">
    <div id="stock-heading">User Transfer</div>
    <div class="sales-fields">
      <div class="sales-boxes">
        <span><%= radio_button "users", "user_type", "1", :onclick=>"makeEnable()" %>To</span> <%= collection_select(:user_name, :technician_id, Technician.all, :id, :name, {:prompt => true}, {:onchange=> "var e=$('name_id'); name_select(e.options[e.selectedIndex].value)", :class => "selectboxLength" } )%>
        <span><%= radio_button "users", "user_type", "2",:onclick=>"makeDisable();" %>From</span> <%= collection_select(:user_name, :technician_id, Technician.all, :id, :name, {:prompt => true}, {:onchange=> "var e=$('name_id'); name_select(e.options[e.selectedIndex].value)", :class => "selectboxLength" } )%>
      </div>
    </div>
    <div class="clear"></div>
    <%=form_for :order, :url => order_create_path, :html => { :onsubmit => "return check_fields()" } do |f| %>
      <div class="clear"></div>
      <div id="dynamic-product-first-row">
        <div class="serial-number-first">S. No.</div>
        <div class="dynamic-name-first">Products/Parts</div>
        <div class="dynamic-description-first">Desciption</div>
        <div class="dynamic-quantity-first">Quantity</div>
        <div class="dynamic-rate-first">Serial Number</div>
        <div class="dynamic-total-first">Challen No.</div>
      </div>
      <div class="clear"></div>
      <div id="1"></div>
      <div class="clear"></div>
      <div class="dynamic_rows"><%= link_to "Add", 'javascript:void(0);', :onclick => "add_row1()" %></div>
      <div class="clear"></div>
      <div class="clear"></div>
      <div id="order-button">
          <%= submit_tag "Stock transfer" %>
      </div>
    <% end %>
    <div id = "left-padding"><%= link_to "Stock Transfer List", product_stock_transfer_details_path%></div>
    </div>
    <div class="clear"></div>
    <div class="bottom_padding"></div>
  </div>
  <div class="clear"></div>
  <div id = "header" align="center"><%= render "layouts/footer" %></div>
<script type="text/javascript">
  function makeDisable(){
    var x=document.getElementById("user_name_id")
    x.disabled=true
  }
  function makeEnable(){
    var x=document.getElementById("user_name_id")
    x.disabled=false
  }
var e=$('users_user_type_1');
  e.checked = true;
window.onload = makeEnable();
</script>
    